databases:
  - name: shopease-db
    databaseName: shopeasedb
    user: postgres
    plan: free

services:

  # The ASP.NET Core Web API backend
  - type: web
    name: shopease-api
    env: docker
    dockerContext: ./backend
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DatabaseProvider
        value: PostgreSQL
      - key: ConnectionStrings__PostgresConnection
        fromDatabase:
          name: shopease-db
          property: connectionString
      - key: UploadProvider
        value: Cloudinary
      - key: Cloudinary__CloudName
        value: dcboricl9
      - key: Cloudinary__ApiKey
        value: "353221611378242"
      - key: Cloudinary__ApiSecret
        value: pUC0an7nD_NwxQglKexA6NKxvEs
      - key: Jwt__Secret
        value: SuperSecretKeyThatIsAtLeast32CharactersLongForSecurityReasons123456
      - key: Jwt__Issuer
        value: ShopEaseBackend
      - key: Jwt__Audience
        value: ShopEaseFrontend
      - key: Jwt__ExpiryInMinutes
        value: "120"

  # The Vite React frontend static site
  - type: web
    name: shopease-frontend
    runtime: static
    plan: free
    rootDir: frontend
    buildCommand: echo "VITE_USE_BACKEND=true" > .env && echo "VITE_API_URL=https://$API_HOST" >> .env && npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: API_HOST
        fromService:
          name: shopease-api
          type: web
          property: host

